my_music/config/routes.rb
MyMusic::Application.routes.draw do
  resources :tracks

  resources :albums

end

my_music/app/models/album.rb
class Album < ActiveRecord::Base
  has_many :tracks

  def as_json(options={})
    super(:include => {:tracks => {:except => :album_id}})
  end 
end

my_music/app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
end

my_music/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, :notice => 'Album was successfully created.' }
        format.json { render :json => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.json { render :json => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, :notice => 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

my_music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

my_music/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, :notice => 'Track was successfully created.' }
        format.json { render :json => @track, :status => :created, :location => @track }
      else
        format.html { render :action => "new" }
        format.json { render :json => @track.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, :notice => 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @track.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end
end

my_music/app/helpers/albums_helper.rb
module AlbumsHelper
end

my_music/app/helpers/application_helper.rb
module ApplicationHelper
end

my_music/app/helpers/tracks_helper.rb
module TracksHelper
end

my_music/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :released %><br />
    <%= f.date_select :released %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

my_music/app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

my_music/app/views/albums/index.html.erb
<h1>My Albums</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Released</th>
    <th>Value</th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.title %></td>
    <td><%= album.artist %></td>
    <td><%= album.released %></td>
    <td><%= album.value %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

my_music/app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

my_music/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @album.title %>
</p>

<p>
  <b>Artist:</b>
  <%= @album.artist %>
</p>

<p>
  <b>Released:</b>
  <%= @album.released %>
</p>

<p>
  <b>Value:</b>
  <%= @album.value %>
</p>

<p>
  <b>Tracks:</b><br />
  <% @album.tracks.each do |track| %>
    <%= link_to track.title, track %><br />
  <% end %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

my_music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMusic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

my_music/app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.text_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

my_music/app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

my_music/app/views/tracks/index.html.erb
<h1>Listing tracks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tracks.each do |track| %>
  <tr>
    <td><%= track.title %></td>
    <td><%= track.length %></td>
    <td><%= link_to 'Show', track %></td>
    <td><%= link_to 'Edit', edit_track_path(track) %></td>
    <td><%= link_to 'Destroy', track, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Track', new_track_path %>

my_music/app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

my_music/app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @track.title %>
</p>

<p>
  <b>Length:</b>
  <%= @track.length %>
</p>


<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>